node1:
  vm_name: node1
  mem_size: 8192
  cpus: 2
  public_ip:  192.168.56.111
  vip_ip:     192.168.56.112
  private_ip: 192.168.200.111
  u01_disk: ./node1_u01.vdi

node2:
  vm_name: node2
  mem_size: 8192
  cpus: 2
  public_ip:  192.168.56.121
  vip_ip:     192.168.56.122
  private_ip: 192.168.200.122
  u01_disk: ./node2_u01.vdi

shared:
  box: oraclelinux/7
  url: 'https://oracle.github.io/vagrant-boxes/boxes/oraclelinux/7.json'
  # ---------------------------------------------
  prefix_name:   ol7-rac
  # ---------------------------------------------
  dns_public_ip: 192.168.56.1
  scan_ip1:      192.168.56.115
  scan_ip2:      192.168.56.116
  scan_ip3:      192.168.56.117
  # ---------------------------------------------
  non_rotational: 'on'
  # ---------------------------------------------
  asm_disk_path:
  asm_disk_num: 4
  asm_disk_size: 20
  # ---------------------------------------------

env:
  gi_software:     LINUX.X64_193000_grid_home.zip
  db_software:     LINUX.X64_193000_db_home.zip
  # ---------------------------------------------
  root_password:   welcome1
  grid_password:   welcome1
  oracle_password: welcome1
  sys_password:    welcome1
  pdb_password:    welcome1
  # ---------------------------------------------
  ora_languages:   en,en_GB
  # ---------------------------------------------
  p1_ratio:        80
  asm_lib_type:    ASMLIB
  nomgmtdb:        true
  orestart:        false
  # ---------------------------------------------
  db_name:         DB193H1
  pdb_name:        PDB1
  db_type:         RAC
  cdb:             false
  # ---------------------------------------------
